build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19
labels:
  org.opencontainers.image.title: "Luftuj"
  org.opencontainers.image.description: "Luftuj Home Assistant Add-on"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.source: "https://github.com/kankajm/Luftuj-HA"
