name: Luftuj
version: 0.1.0
slug: luftuj
description: Luftuj Home Assistant Add-on
url: https://github.com/kankajm/Luftuj-HA
arch:
  - aarch64
  - amd64
  - armv7
init: false
startup: services
homeassistant_api: true
hassio_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:valve
discovery: []
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
